server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/containers/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
      - regex:
          expression: (?P<container_name>(?:[^_|]+))_(?:[^_|]+)_(?P<container_id>[^_]+)
          source: attrs.tag
      - labels:
          container_name: container_name
          container_id: container_id
      - timestamp:
          format: RFC3339Nano
          source: time
      - output:
          source: stream

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

    pipeline_stages:
      - match:
          selector: '{job="varlogs"}'
          stages:
            - multiline:
                firstline: '^\w{3} \d{1,2} \d{2}:\d{2}:\d{2}'
                max_wait_time: 3s
            - regex:
                expression: '^(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2}) (?P<hostname>\w+) (?P<program>\w+)\[(?P<pid>\d+)\]: (?P<message>.*)$'
            - labels:
                hostname: hostname
                program: program
                pid: pid
            - timestamp:
                format: "Jan _2 15:04:05"
                source: timestamp
            - output:
                source: message
