global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
    scrape_interval: 30s

  - job_name: "backend"
    static_configs:
      - targets: ["backend:4000"]
    scrape_interval: 30s
    metrics_path: "/metrics"

  - job_name: "nextjs"
    static_configs:
      - targets: ["nextjs:3000"]
    scrape_interval: 30s

  - job_name: "ipfs-service"
    static_configs:
      - targets: ["ipfs-service:5001"]
    scrape_interval: 30s

  - job_name: "regru"
    static_configs:
      - targets: ["regru:4001"]
    scrape_interval: 30s

  - job_name: "smart-contracts"
    static_configs:
      - targets: ["smart-contracts:8545"]
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
