name: 🚀 Deployment Issue
description: Report deployment-related issues
title: "[DEPLOY] "
labels: ["deployment", "infrastructure"]
body:
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: Service
      description: Which service is affected?
      options:
        - Frontend (Next.js)
        - Backend (Node.js)
        - IPFS Service
        - Smart Contracts
        - Database
        - All Services
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the deployment issue
      placeholder: Detailed description of the problem
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant logs or error messages
      render: shell