replicaCount: 3

image:
  registry: ghcr.io
  repository: aendystudio/normaldance-nextjs
  pullPolicy: Always

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

backend:
  enabled: true
  replicaCount: 3
  image:
    repository: aendystudio/normaldance-backend
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

ipfs:
  enabled: true
  replicaCount: 2
  image:
    repository: aendystudio/normaldance-ipfs
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

contracts:
  enabled: true
  replicaCount: 1
  image:
    repository: aendystudio/normaldance-contracts

postgresql:
  enabled: true
  auth:
    postgresPassword: "CHANGE_ME_IN_PRODUCTION"
    username: normaldance
    password: "CHANGE_ME_IN_PRODUCTION"
    database: normaldance
  primary:
    persistence:
      enabled: true
      size: 50Gi
      storageClass: "fast-ssd"
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: "CHANGE_ME_IN_PRODUCTION"
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: normaldance.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: normaldance-tls
      hosts:
        - normaldance.com

env:
  NODE_ENV: production
  SOLANA_RPC_URL: "https://api.mainnet-beta.solana.com"
  IPFS_GATEWAY_URL: "https://ipfs.io/ipfs/"