global:
  imageRegistry: ""
  imagePullSecrets: []

replicaCount: 2

image:
  registry: ghcr.io
  repository: aendystudio/normaldance
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext:
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: normaldance.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: normaldance-tls
      hosts:
        - normaldance.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Backend service configuration
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: aendystudio/normaldance-backend
    tag: ""
  service:
    port: 8080
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

# IPFS service configuration
ipfs:
  enabled: true
  replicaCount: 1
  image:
    repository: aendystudio/normaldance-ipfs
    tag: ""
  service:
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Smart contracts service
contracts:
  enabled: true
  replicaCount: 1
  image:
    repository: aendystudio/normaldance-contracts
    tag: ""
  service:
    port: 8545

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: ""
    username: normaldance
    password: ""
    database: normaldance
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: ""

# Environment variables
env:
  NODE_ENV: production
  DATABASE_URL: ""
  REDIS_URL: ""
  SOLANA_RPC_URL: ""
  IPFS_GATEWAY_URL: ""