apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "normaldance.fullname" . }}-config
  labels:
    {{- include "normaldance.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: "3000"
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:$(POSTGRES_PASSWORD)@{{ include "normaldance.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  {{- else }}
  DATABASE_URL: {{ .Values.env.DATABASE_URL | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@{{ include "normaldance.fullname" . }}-redis-master:6379"
  {{- else }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  {{- end }}
  SOLANA_RPC_URL: {{ .Values.env.SOLANA_RPC_URL | default "https://api.mainnet-beta.solana.com" | quote }}
  IPFS_GATEWAY_URL: {{ .Values.env.IPFS_GATEWAY_URL | default "https://ipfs.io/ipfs/" | quote }}
  BACKEND_URL: "http://{{ include "normaldance.fullname" . }}-backend:{{ .Values.backend.service.port }}"
  IPFS_SERVICE_URL: "http://{{ include "normaldance.fullname" . }}-ipfs:{{ .Values.ipfs.service.port }}"