apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "normaldance.fullname" . }}
  labels:
    {{- include "normaldance.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "normaldance.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
    - from:
        - podSelector:
            matchLabels:
              {{- include "normaldance.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "normaldance.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - podSelector:
            matchLabels:
              {{- include "normaldance.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: ipfs
      ports:
        - protocol: TCP
          port: 8080
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80