name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20.10.0"
  NEXT_TELEMETRY_DISABLED: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  quick-checks:
    name: Quick Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run type check
        run: npm run type-check
        continue-on-error: true
      - name: Run linting
        run: npm run lint
        continue-on-error: true

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run security audit
        run: npm audit --audit-level=high
        continue-on-error: true

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --passWithNoTests
        env:
          CI: true

  build-app:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [quick-checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production
          SKIP_ENV_VALIDATION: true

  build-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [unit-tests, build-app]
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service:
          [nextjs, backend, ipfs-service, regru, smart-contracts, postgres]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-images
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: "3.12.0"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "1.28.0"
      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
      - name: Run database migrations
        run: |
          kubectl create job --from=cronjob/normaldance-migration migration-$(date +%s) || true
          kubectl wait --for=condition=complete --timeout=300s job/migration-$(date +%s)
      - name: Helm upgrade/install
        run: |
          helm upgrade --install normaldance ./helm/normaldance \
            --namespace production \
            --create-namespace \
            --set image.tag=${{ github.sha }} \
            --set backend.image.tag=${{ github.sha }} \
            --set ipfs.image.tag=${{ github.sha }} \
            --set contracts.image.tag=${{ github.sha }} \
            --values ./helm/normaldance/values-production.yaml \
            --wait --timeout=10m
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/normaldance -n production
          kubectl get pods -n production
